Develop
chuckytsai/taipei-day-trip-website pull request #3
Opened 2021-04-26 15:31 UTC by chuckytsai

蔡忠和
http://35.73.243.150:3000/api/attractions?page=0
http://35.73.243.150:3000/api/attractions?page=0&keyword=北
http://35.73.243.150:3000/api/attraction?id=0

2021-04-26 15:58 UTC, cwpeng requested changes
測試網址無法運作。

2021-04-26 16:21 UTC, chuckytsai commented
老師請您在連接看看  謝謝

2021-04-26 16:31 UTC, cwpeng commented
我們的單一景點 API 應該是長像以下這樣的，景點編號直接從路徑取得：
http://35.73.243.150:3000/api/attraction/1
http://35.73.243.150:3000/api/attraction/279

請調整完再發 REVIEW 的要求給我哦 ~

2021-04-27 03:25 UTC, chuckytsai commented
蔡忠和
http://35.73.243.150:3000/api/attractions?page=0
http://35.73.243.150:3000/api/attractions?page=0&keyword=%E5%8C%97
http://35.73.243.150:3000/api/attraction/1

老師再麻煩您過目  謝謝

2021-04-27 06:37 UTC, cwpeng commented
結果是可以，但請重新發 Review 的要求給我，才有辦法幫你 Approve ~

雖然結果還 OK，但你的程式非常嚴重的沒有效率，例如抓取景點的資訊，應該要一次抓取全部，而不是一個一個分開抓，這點就請你盡可能改進，不然丟給其他人看的時候，很難被青睞。

2021-04-27 07:10 UTC, chuckytsai commented
老師  我知道會慢得可怕  我原本抱著會被您退這件事情的心情
不過上周超過我極限了
我會找時間再修改
謝謝提醒

2021-04-27 07:29 UTC, cwpeng commented
我主要是看結果，所以勉強接受。但我得和你說這個嚴重性，是會影響你找工作的結果的。

2021-04-27 08:29 UTC, chuckytsai commented
蔡忠和
http://35.73.243.150:3000/api/attractions?page=0
http://35.73.243.150:3000/api/attractions?page=0&keyword=%E5%8C%97
http://35.73.243.150:3000/api/attraction/1

2021-04-27 08:49 UTC, merged