Develop
chuckytsai/taipei-day-trip-website pull request #7
Opened 2021-05-17 06:14 UTC by chuckytsai

http://35.73.243.150:3000/
http://35.73.243.150:3000/attraction/9
蔡忠和

2021-05-17 23:04 UTC, cwpeng commented
網站似乎是連不上哦，請恢復後和我說 ~

2021-05-18 01:46 UTC, chuckytsai commented
老師  再麻煩您重連一次看看

2021-05-18 04:03 UTC, cwpeng requested changes
會員功能沒問題，但你的手機版面的導覽列會嚴重跑版，請修正哦：
![35 73 243 150_3000_](https://user-images.githubusercontent.com/6104683/118588472-067f8380-b7d1-11eb-88b5-dd9e455d43a2.png)

2021-05-18 06:37 UTC, chuckytsai commented
2021/05/18
已修改,再勞煩您過目
謝謝

2021-05-18 06:40 UTC, cwpeng commented
看起來沒問題了，但請記得重新發 Review Request 給我，下次不會再提醒了，我會直接忽略哦 ~

2021-05-18 06:46 UTC, cwpeng approved these changes
OK ~

2021-05-18 06:49 UTC, merged